language: csharp
solution: TetrisVideoGame.sln
mono:
- latest

install:
  - nuget restore TetrisVideoGame.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TetrisVideoGame.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll